export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'

export const CURRENT_USER_POSTS_UPDATE = 'CURRENT_USER_POSTS_UPDATE'
export const CHATS_SET = 'CHATS_SET'


export const MODAL_OPEN_COMMENT_SECTION = 'MODAL_OPEN_COMMENT_SECTION'
export const CLEAR_MODAL = 'CLEAR_MODAL'